#!/bin/sh
COPYTO="sfxc@master2:/home/sfxc/kana"

cd "${0%/*}"
ssh -o ProxyCommand="ssh -p 222 -W master2:222 sfxc@10.0.10.10" sfxc@master2 "rm -r /home/sfxc/kana"
ssh -o ProxyCommand="ssh -p 222 -W master2:222 sfxc@10.0.10.10" sfxc@master2 "mkdir -p /home/sfxc/kana"
scp -o ProxyCommand="ssh -p 222 -W master2:222 sfxc@10.0.10.10" Makefile $COPYTO
scp -o ProxyCommand="ssh -p 222 -W master2:222 sfxc@10.0.10.10" kana.py $COPYTO
scp -o ProxyCommand="ssh -p 222 -W master2:222 sfxc@10.0.10.10" -r correlator-kana $COPYTO
ssh -o ProxyCommand="ssh -p 222 -W master2:222 sfxc@10.0.10.10" sfxc@master2 "source ~/.profile && cd /home/sfxc/kana && make"