all:
	@cd ./correlator-kana/mode1 && $(MAKE) --no-print-directory
	@cd ./correlator-kana/mode2 && $(MAKE) --no-print-directory
	@cd ./correlator-kana/mode3 && $(MAKE) --no-print-directory
	@cd ./correlator-kana/freqCorrect && $(MAKE) --no-print-directory
	@cd ./correlator-kana/timeCorrect && $(MAKE) --no-print-directory
	@cd ./correlator-kana/dataSender && $(MAKE) --no-print-directory

mode1:
	@cd ./correlator-kana/mode1 && $(MAKE) --no-print-directory

mode2:
	@cd ./correlator-kana/mode2 && $(MAKE) --no-print-directory

mode3:
	@cd ./correlator-kana/mode3 && $(MAKE) --no-print-directory

freqCorrect:
	@cd ./correlator-kana/freqCorrect && $(MAKE) --no-print-directory

timeCorrect:
	@cd ./correlator-kana/timeCorrect && $(MAKE) --no-print-directory

dataSender:
	@cd ./correlator-kana/dataSender && $(MAKE) --no-print-directory